spring:
  application:
    name: ai-langchain4j

  profiles:
    active: local


  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848

  config:
    import:
      - nacos:ai-video.yml

server:
  port: 9432



