#dashborad:
#  base-url: https://dashscope.aliyuncs.com/api/v1
#  api-key: sk-c1a97acf167c42eb98464344a7157a8a
#  model-name: text-embedding-v2


langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-plus
        api-key: sk-c1a97acf167c42eb98464344a7157a8a
      embedding-model:
        model-name: text-embedding-v2
        api-key: sk-c1a97acf167c42eb98464344a7157a8a
      streaming-chat-model:
        model-name: qwen-plus
        api-key: sk-c1a97acf167c42eb98464344a7157a8a
