spring:
  application:
    name: ai-asr

  profiles:
    active: local


  servlet:
    multipart:
        max-file-size: 50MB
        max-request-size: 50MB
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
  config:
    import:
      - nacos:ai-asr.yml



server:
  port: 8432



